### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by ryanguest**

### CODE REVIEW

**Comment by PauloASilva** [comment]
Hi @ryanguest ,
Can you please open a Pull Request to our `develop` branch?

On release v1.1 I will try to improve the [How To Contribute section][1] so that community members can open `hotfix` branches: we follow the [A successful Git branching model][2] by Vincent Driessen.

Thanks for your careful review,
Paulo

[1]: https://github.com/Checkmarx/Go-SCP/blob/master/src/howto-contribute.md
[2]: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by PauloASilva** [comment]
As I wasn't able to hear from you, I did apply the patch myself: https://github.com/Checkmarx/Go-SCP/commit/09445cfad4793fc0718f0457c444ca79b69f7642

Thanks,
Paulo A. Silva

**Comment by ryanguest** [comment]
beat me to it @PauloASilva .

Thanks for taking the time to pull these in yourself!

**Comment by PauloASilva** [comment]
Hi @ryanguest ,
You're welcome ;)

Thanks again for your contribution.

Best,
Paulo A. Silva

**Pull request closed without merging**
