### PR TITLE
show example of placeholder syntax

### PR DESCRIPTION
**Pull request by nicobouliane**
The example have been taken here:
http://go-database-sql.org/prepared.html

their text is licensed under crative common.

### CODE REVIEW

**Comment by PauloASilva** [comment]
Hi @nicobouliane,
I think it will be better putting the footnote and your contribution inline with the text: as it is now, makes the footnote bigger than a footnote should be.

Please see the suggested patch: [pr-20.txt](https://github.com/Checkmarx/Go-SCP/files/950693/pr-20.txt)

Regards,
Paulo

**Comment by PauloASilva** [comment]
Hi @nicobouliane,
We're about to release the version v1.1 and we would be glad to add your contribution.
Can you please review my previous comment and the attached patch?

Regards,
Paulo

**Comment by PauloASilva** [comment]
This would fix #20

**Comment by nicobouliane** [comment]
Hi ! I have updated the pull request based on your patch review !
Sorry for the delay, I'm currently on vacation :)

**Comment by PauloASilva** [comment]
Hi @nicobouliane,
Sorry about messing with your vacation time.

Last request: can you please open the Pull Request to our `develop` branch?
We're following Vincent Driessen's [A successful Git branching model][1] taking advantage of [Gitflow][2] and [Git Flow Hooks][3] as explained in [How To Contribute section][4]: it is of a great help managing releases, hotfixes, etc. but we should make it clear on README.

Best,
Paulo

[1]: http://nvie.com/posts/a-successful-git-branching-model/
[2]: https://github.com/petervanderdoes/gitflow-avh
[3]: https://github.com/jaspernbrouwer/git-flow-hooks
[4]: https://github.com/Checkmarx/Go-SCP/blob/master/src/howto-contribute.md#how-to-contribute]

**Comment by PauloASilva** [comment]
I will close this: [PR#30](https://github.com/Checkmarx/Go-SCP/pull/30) did it.

**Pull request closed without merging**
