### PR TITLE
Use bcrypt for password hashing instead of manual hashing and salting

### PR DESCRIPTION
**Pull request by gilliek**
This PR replaces manual hashing and salting by bcrypt and gives good practices about password hashing.

### CODE REVIEW

**Comment by PauloASilva** [comment]
Hi @gilliek,
Again, nice contribution.

While writing this section we have consciously opted by showing the "hashing with salt" process so that readers can understand exactly what "salted hashes" are.

I agree that `bcrypt` is the proper way to go, but for educational purposes, what do you think about keeping both examples? Would you be available to rewrite your contribution?

Argon2 desired a reference: we can link the [the reference C implementation of Argon2 on Github][1]

Best,
Paulo
[1]: https://github.com/p-h-c/phc-winner-argon2

**Comment by PauloASilva** [comment]
Something we should demonstrate while using [Go's bcrypt implementation][1] is how to compare a given password with a hash ([CompareHashAndPassword][2]) as it may be not clear to everyone.

Regards,
Paulo

[1]: https://godoc.org/golang.org/x/crypto/bcrypt
[2]: https://godoc.org/golang.org/x/crypto/bcrypt#CompareHashAndPassword

**Comment by gilliek** [comment]
Hi @PauloASilva,

I agree, it could be interesting to have both examples as well as an example of how using the CompareHashAndPassword function. I'll update the PR.

Best,
Kevin

**Comment by gilliek** [comment]
Hi @PauloASilva,

I've updated the PR with your suggestions.

Best,
Kevin

**Comment by PauloASilva** [comment]
@gilliek,
Awesome work 👍.

Best,
Paulo

**Pull request merged**
